S1AvgBSt.test(S1AvgBS ~ Scen)$p.valuet.test(S1AvgBS ~ Scen)$t.test(S1AvgBS ~ Scen)$
S1AvgPIt.test(S1AvgPI ~ Scen)$p.valuet.test(S1AvgPI ~ Scen)$t.test(S1AvgPI ~ Scen)$
S1AvgTFt.test(S1AvgTF ~ Scen)$p.valuet.test(S1AvgTF ~ Scen)$t.test(S1AvgTF ~ Scen)$
S1AvgMAt.test(S1AvgMA ~ Scen)$p.valuet.test(S1AvgMA ~ Scen)$t.test(S1AvgMA ~ Scen)$
S1AvgBRt.test(S1AvgBR ~ Scen)$p.valuet.test(S1AvgBR ~ Scen)$t.test(S1AvgBR ~ Scen)$
S1AvgBSt.test(S1AvgBS ~ Scen)$p.valuet.test(S1AvgBS ~ Scen)$t.test(S1AvgBS ~ Scen)$
S2AvgPIt.test(S2AvgPI ~ Scen)$p.valuet.test(S2AvgPI ~ Scen)$t.test(S2AvgPI ~ Scen)$
S2AvgTFt.test(S2AvgTF ~ Scen)$p.valuet.test(S2AvgTF ~ Scen)$t.test(S2AvgTF ~ Scen)$
S2AvgMAt.test(S2AvgMA ~ Scen)$p.valuet.test(S2AvgMA ~ Scen)$t.test(S2AvgMA ~ Scen)$
S2AvgBRt.test(S2AvgBR ~ Scen)$p.valuet.test(S2AvgBR ~ Scen)$t.test(S2AvgBR ~ Scen)$
S2AvgBSt.test(S2AvgBS ~ Scen)$p.valuet.test(S2AvgBS ~ Scen)$t.test(S2AvgBS ~ Scen)$
S3AvgPIt.test(S3AvgPI ~ Scen)$p.valuet.test(S3AvgPI ~ Scen)$t.test(S3AvgPI ~ Scen)$
S3AvgTFt.test(S3AvgTF ~ Scen)$p.valuet.test(S3AvgTF ~ Scen)$t.test(S3AvgTF ~ Scen)$
S3AvgMAt.test(S3AvgMA ~ Scen)$p.valuet.test(S3AvgMA ~ Scen)$t.test(S3AvgMA ~ Scen)$
S3AvgBRt.test(S3AvgBR ~ Scen)$p.valuet.test(S3AvgBR ~ Scen)$t.test(S3AvgBR ~ Scen)$
S3AvgBSt.test(S3AvgBS ~ Scen)$p.valuet.test(S3AvgBS ~ Scen)$t.test(S3AvgBS ~ Scen)$
S4AvgPIt.test(S4AvgPI ~ Scen)$p.valuet.test(S4AvgPI ~ Scen)$t.test(S4AvgPI ~ Scen)$
S4AvgTFt.test(S4AvgTF ~ Scen)$p.valuet.test(S4AvgTF ~ Scen)$t.test(S4AvgTF ~ Scen)$
S4AvgMAt.test(S4AvgMA ~ Scen)$p.valuet.test(S4AvgMA ~ Scen)$t.test(S4AvgMA ~ Scen)$
S4AvgBRt.test(S4AvgBR ~ Scen)$p.valuet.test(S4AvgBR ~ Scen)$t.test(S4AvgBR ~ Scen)$
S4AvgBSt.test(S4AvgBS ~ Scen)$p.valuet.test(S4AvgBS ~ Scen)$t.test(S4AvgBS ~ Scen)$